### PR TITLE
Remove regression detection from issue bot in favor of peril

### PR DESCRIPTION
**Pull request by KrauseFx**
New code lives in https://github.com/fastlane/peril-settings

### CODE REVIEW

**Comment by KrauseFx** [comment]
Yo

**Comment by KrauseFx** [comment]
@joshdholtz

**Comment by joshdholtz** [comment]
@KrauseFx Hey, sorry! Was on my honeymoon for two weeks and just got back this week 😊 Will handle

**Comment by mollyIV** [comment]
> I think this should be GH actions now actually

Really like this idea ❤️ We already started working on GitHub Actions migration: https://github.com/fastlane/fastlane/pull/15229 🙇

**Comment by KrauseFx** [comment]
Awesome, closing this one

**Pull request closed without merging**
