### PR TITLE
Added auto-posting of signing information

### PR DESCRIPTION
**Pull request by KrauseFx**
Reply looks like this https://github.com/fastlane/issue-bot/issues/3#issuecomment-229075888

### CODE REVIEW

**Comment by ohwutup** [comment]
💯 this is awesome! So great to try to get in front of code signing issues! 🚀

**Comment by KrauseFx** [comment]
Perfect, I'll update the URL once https://github.com/fastlane/fastlane/pull/5178 gets merged

**Comment by KrauseFx** [comment]
Updated the URL 👍

**Comment by mfurtak** [comment]
👍

**Pull request merged**
