### PR TITLE
Add minimal development documentation

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by revolter** [comment]
@milch, Any feedback? 😃

**Comment by revolter** [comment]
Waaait, you can use that `rake` tool for this?

**Comment by milch** [comment]
What do you mean with the `rake` comment?

**Comment by revolter** [comment]
Just saw that there is a `Rakefile` and it looks like tasks for running different bot actions.

**Comment by revolter** [comment]
Yep, you can simply run `bundle exec rake process_issues` :| I need to another commit to this.

**Comment by revolter** [comment]
@milch, This should be done now.

**Comment by KrauseFx** [comment]
🎉

**Pull request merged**
